baseURL = 'https://stalinon.github.io/'
publishDir = "public"
languageCode = "ru"
title = "Egor Fedorov"
defaultContentLanguage = "ru"
enableMissingTranslationPlaceholders = true
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    title = "Egor Fedorov"
    
  [languages.ru]
    languageName = "Русский"
    weight = 2
    contentDir = "content/ru"
    title = "Егор Фёдоров"
